import "../styles/globals.css";
import Header from "@/components/section/Header";
import LenisWrapper from "@/components/utils/LenisWrapper"; // We'll make this next
import PageTransition from "@/components/PageTransition";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        
      </head>
      <body>
      <PageTransition>
        <LenisWrapper>
          <Header />
          {children}
        </LenisWrapper>
        </PageTransition>
      </body>
    </html>
  );
}
