import "../styles/globals.css";
import Header from "@/section/Header";
import LenisWrapper from "@/utils/LenisWrapper"; // We'll make this next

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        
      </head>
      <body>
        <LenisWrapper>
          <Header />
          {children}
        </LenisWrapper>
      </body>
    </html>
  );
}
