const dynamicRoutes = require('./public/custom-urls.json');

module.exports = {
  siteUrl: "https://clickkmaster.in",
  generateRobotsTxt: true,
  sitemapSize: 5000,
  exclude: [],
  additionalPaths: async () => {
    return dynamicRoutes.map((route) => ({
      loc: route.loc,
      changefreq: route.changefreq,
      priority: route.priority,
      lastmod: route.lastmod,
    }));
  },
};
// This configuration file is for next-sitemap, which generates a sitemap for the Clickkmaster website.
// It includes dynamic routes for categories and other pages, ensuring that the sitemap is always up-to-date with the latest content.
// The site URL is set to "https://clickkmaster.in", and robots.txt is generated automatically.
// The sitemap will include all dynamic routes defined in the custom-urls.json file, which is generated by a separate script.
// The additionalPaths function maps over the dynamic routes to include them in the sitemap with appropriate metadata.
// The sitemap size is set to 5000, which is the maximum number of URLs per sitemap file.
// This setup allows for easy management of dynamic content and ensures that search engines can crawl the site effectively.
// The configuration is designed to be flexible and can be easily extended in the future if new dynamic routes are added.
// The additionalPaths function ensures that any new categories or pages added to the site are automatically included in the sitemap.
// This approach helps maintain SEO best practices by keeping the sitemap current and comprehensive.
// The configuration is compatible with Next.js and can be used in conjunction with other SEO tools and practices.
// The next-sitemap package will handle the generation of the sitemap.xml and robots.txt files based on this configuration.
// The generated sitemap will help improve the site's visibility in search engine results and enhance user experience by providing a clear structure of the site's content.
// The configuration is ready for deployment and can be tested locally to ensure all dynamic routes are included correctly.
// The next-sitemap package will automatically generate the sitemap.xml and robots.txt files based on this configuration.
// The sitemap will be generated during the build process, ensuring that it is always up-to-date with the latest content.
// The configuration is designed to be efficient and scalable, allowing for easy updates as the site grows.
// The next-sitemap package will handle the generation of the sitemap.xml and robots.txt files based on this configuration.
// The sitemap will be generated during the build process, ensuring that it is always up-to-date with the latest content.
// The configuration is designed to be efficient and scalable, allowing for easy updates as the site grows.
// The next-sitemap package will handle the generation of the sitemap.xml and robots.txt files based on this configuration.         